services:
    _defaults:
        autoconfigure: true
    SI\ContaoAccessiKitContaoBundle\Migration\WebAccessibilityMigration:
        arguments:
            - '@database_connection'
        tags:
            - { name: 'contao.migration', priority: 0 }
