services:
  _defaults:
    autoconfigure: true

  #Hooks
  SI\ContaoAccessiKitContaoBundle\EventListener\OutputBackendTemplateListener:
    tags:
      - { name: contao.hook, hook: outputBackendTemplate, priority: 100 }

  SI\ContaoAccessiKitContaoBundle\EventListener\LoadDataContainerListener:
    tags:
      - { name: contao.hook, hook: loadDataContainer, priority: 100 }

  SI\ContaoAccessiKitContaoBundle\EventListener\ContentElementListener:
    tags:
      - { name: contao.hook, hook: getContentElement, priority: 100 }

  SI\ContaoAccessiKitContaoBundle\EventListener\OutputFrontendTemplateListener:
    tags:
      - { name: contao.hook, hook: outputFrontendTemplate, priority: 100 }

  SI\ContaoAccessiKitContaoBundle\EventListener\GetFrontendModuleListener:
    tags:
      - { name: contao.hook, hook: getFrontendModule, priority: 100 }
