services:
  _defaults:
    autoconfigure: true

  #Hooks
  SI\ContaoAccessiKitContaoBundle\EventListener\OutputBackendTemplateListener:
    tags:
      - { name: contao.hook, hook: outputBackendTemplate, priority: 100 }

  SI\ContaoAccessiKitContaoBundle\EventListener\LoadDataContainerListener:
    tags:
      - { name: contao.hook, hook: loadDataContainer, priority: 100 }
